volumes:
  postgres-data:
    external: true
  pg-admin:
    external: true

services:
  postgres:
    build:
      context: ./relational-data
      dockerfile: ./Dockerfile.dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_MULTIPLE_DATABASES=hikes
      - POSTGRES_PASSWORD=test-databases
    ports:
      - 15432:5432

  hikes-api:
    build:
      context: hikes_api_service
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ./hikes_api_service:/app
    environment:
      SIGNING_KEY: ewioj23j2io3j4e23joj54oij32i5j423oij4io32jojio32jiore2oi3jr4io432jorij3ornf45rgnoi456yg54
      WAIT_BEFORE: 10
      WAIT_TIMEOUT: 60
      DATABASE_URL: postgresql://hikes:password@postgres/hikes
      WAIT_HOSTS: postgres:5432

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_HIKES_API_SERVICE_API_HOST: ${REACT_APP_HIKES_API_SERVICE_API_HOST}

  pg-admin:
    image: dpage/pgadmin4
    volumes:
      - pg-admin:/var/lib/pgadmin
    ports:
      - 8082:80
    environment:
      PGADMIN_DEFAULT_EMAIL: email@email.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_DISABLE_POSTFIX: 1
